/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as basicTokenSol from "./BasicToken.sol";
export type { basicTokenSol };
export type { Lock } from "./Lock";
export type { TransferContract } from "./TransferContract";
export type { WillExecutor } from "./WillExecutor";
export type { WillProtocol } from "./WillProtocol";
