/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as basicTokenSol from "./BasicToken.sol";
export { Lock__factory } from "./Lock__factory";
export { TransferContract__factory } from "./TransferContract__factory";
export { WillExecutor__factory } from "./WillExecutor__factory";
export { WillProtocol__factory } from "./WillProtocol__factory";
